create table if not exists public.team_sessions (id uuid primary key default gen_random_uuid(), team_id uuid references public.teams(id) on delete cascade, auth_user_id uuid references auth.users(id) on delete cascade, expires_at timestamptz not null, created_at timestamptz default now());
create table if not exists public.volunteer_assignments (volunteer_id uuid references auth.users(id) on delete cascade, checkpoint_id uuid references public.checkpoints(id) on delete cascade, primary key(volunteer_id, checkpoint_id));
create or replace function public.operator_role() returns text language sql stable as $$ select coalesce(auth.jwt()->'app_metadata'->>'role', auth.jwt()->'user_metadata'->>'role', '') $$;
create or replace function public.is_admin() returns boolean language sql stable as $$ select public.operator_role() in ('admin','super_admin') $$;
create or replace function public.is_event_control() returns boolean language sql stable as $$ select public.operator_role() in ('admin','super_admin','event_control') $$;
create or replace function public.is_assigned_volunteer(checkpoint uuid) returns boolean language sql stable as $$ select public.operator_role() = 'volunteer' and exists (select 1 from public.volunteer_assignments where volunteer_id = auth.uid() and checkpoint_id = checkpoint) $$;
alter table public.events enable row level security;
alter table public.checkpoints enable row level security;
alter table public.routes enable row level security;
alter table public.team_routes enable row level security;
alter table public.team_progress enable row level security;
alter table public.fragments enable row level security;
alter table public.team_fragments enable row level security;
alter table public.hints enable row level security;
alter table public.hint_usage enable row level security;
alter table public.offline_tokens enable row level security;
alter table public.final_attempts enable row level security;
alter table public.audit_logs enable row level security;
alter table public.event_settings enable row level security;
do $$ begin
  drop policy if exists events_operator_read on public.events;
  drop policy if exists events_operator_write on public.events;
  drop policy if exists checkpoints_operator_read on public.checkpoints;
  drop policy if exists checkpoints_admin_write on public.checkpoints;
  drop policy if exists progress_operator_read on public.team_progress;
  drop policy if exists progress_service_write on public.team_progress;
  drop policy if exists audit_operator_read on public.audit_logs;
  drop policy if exists settings_admin_all on public.event_settings;
exception when undefined_object then null; end $$;
create policy events_operator_read on public.events for select using (public.is_event_control() or public.operator_role() = 'volunteer');
create policy events_operator_write on public.events for all using (public.is_admin()) with check (public.is_admin());
create policy checkpoints_operator_read on public.checkpoints for select using (public.is_event_control() or public.operator_role() = 'volunteer');
create policy checkpoints_admin_write on public.checkpoints for all using (public.is_admin()) with check (public.is_admin());
create policy progress_operator_read on public.team_progress for select using (public.is_event_control() or public.is_assigned_volunteer(checkpoint_id));
create policy progress_service_write on public.team_progress for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy audit_operator_read on public.audit_logs for select using (public.is_event_control());
create policy settings_admin_all on public.event_settings for all using (public.is_admin()) with check (public.is_admin());