create extension if not exists pgcrypto;
create type public.event_state as enum ('STANDBY','LIVE','PAUSED','ENDED');
create type public.team_status as enum ('active','finished','disabled');
create table if not exists public.events (id uuid primary key default gen_random_uuid(), name text not null, state public.event_state not null default 'STANDBY', starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.teams (id uuid primary key default gen_random_uuid(), team_id text unique not null, team_name text not null, pin_hash text not null, status public.team_status not null default 'active', created_at timestamptz not null default now());
create table if not exists public.team_members (id uuid primary key default gen_random_uuid(), team_id uuid references public.teams(id) on delete cascade, display_name text not null, created_at timestamptz default now());
create table if not exists public.checkpoints (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, description text, clue text not null, challenge text not null, answer_hash text not null, fragment text not null, points integer not null default 120, created_at timestamptz default now());
create table if not exists public.routes (id uuid primary key default gen_random_uuid(), name text not null, checkpoint_order text[] not null);
create table if not exists public.team_routes (team_id uuid references public.teams(id) on delete cascade, route_id uuid references public.routes(id), primary key(team_id));
create table if not exists public.team_progress (id uuid primary key default gen_random_uuid(), team_id uuid references public.teams(id) on delete cascade, checkpoint_id uuid references public.checkpoints(id), route_position integer not null, status text not null default 'locked', score integer not null default 0, completed_at timestamptz, unique(team_id,checkpoint_id));
create table if not exists public.fragments (id uuid primary key default gen_random_uuid(), checkpoint_id uuid references public.checkpoints(id), value text not null);
create table if not exists public.team_fragments (team_id uuid references public.teams(id) on delete cascade, fragment_id uuid references public.fragments(id), collected_at timestamptz default now(), primary key(team_id,fragment_id));
create table if not exists public.hints (id uuid primary key default gen_random_uuid(), checkpoint_id uuid references public.checkpoints(id), name text not null, content text not null, penalty integer not null);
create table if not exists public.hint_usage (id uuid primary key default gen_random_uuid(), team_id uuid references public.teams(id), hint_id uuid references public.hints(id), used_at timestamptz default now());
create table if not exists public.volunteers (id uuid primary key references auth.users(id) on delete cascade, checkpoint_id uuid references public.checkpoints(id), display_name text not null, role text not null default 'volunteer');
create table if not exists public.offline_tokens (id uuid primary key default gen_random_uuid(), token text unique not null, team_id uuid references public.teams(id), checkpoint_id uuid references public.checkpoints(id), used_at timestamptz, issued_at timestamptz default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), message text not null, active boolean default true, created_at timestamptz default now());
create table if not exists public.final_attempts (id uuid primary key default gen_random_uuid(), team_id uuid references public.teams(id), answer_hash text not null, is_valid boolean not null default false, attempted_at timestamptz default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), action text not null, actor_type text not null, actor_id uuid, team_id uuid references public.teams(id), metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.event_settings (key text primary key, value jsonb not null);
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.volunteers enable row level security;
alter table public.announcements enable row level security;
create policy "admins manage teams" on public.teams for all using (auth.jwt()->>'role' in ('service_role','admin')) with check (auth.jwt()->>'role' in ('service_role','admin'));
create policy "volunteers read announcements" on public.announcements for select using (active = true);
do $$ begin
  alter publication supabase_realtime add table public.events, public.announcements, public.team_progress, public.audit_logs;
exception when duplicate_object then null;
end $$;